import os
import sys
import glob

Import("globalenv IsLinux IsWindows IsDarwin LibraryInstall compiler builddir")

libt5 = globalenv.SharedLibrary("t5", glob.glob("*.cpp"), CPPDEFINES = ["T5_INTERNAL=1"])
#t5convert = globalenv.Program("t5conv", os.path.join("t5convert", "main.cpp"), CPPPATHS = [os.getcwd()], LIBS=[libt5], LIBPATH = ["./"])

LibraryInstall(builddir, libt5, globalenv)
#globalenv.Install(builddir, [t5convert])

Return("libt5")
